name: AlouUtils
version: '${version}'
main: fr.alouchi.alouutils.AlouUtils
commands:
  enderchest:
    permission: enderchest.au
  feed:
    permission: feed.au
  fly:
    permission: fly.au
  gm:
    permission: gm.au
  god:
    permission: god.au
  heal:
    permission: heal.au
  kickall:
    permission: kickall.au